alias cfv="$EDITOR ${HOME}/.vim/vimrc"
alias cfz="$EDITOR ${HOME}/.config/zsh/.zshrc"
alias cfa="$EDITOR ${CONFIGS_REPO}/shell/aliasrc.sh"
alias cfp="$EDITOR ${CONFIGS_REPO}/shell/profile.sh"
alias cfs="$EDITOR ${CONFIGS_REPO}/shell/shortcuts.sh"
