source $XDG_CONFIG_HOME/env/varrc

CASE_SENSITIVE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="false"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
	git
	git-prompt
	gitignore
	sudo
	vi-mode
	rustup
	rust
	hitchhiker
	fzf
	colorize
	colored-man-pages
	zsh-autosuggestions
)

# colorize
ZSH_COLORIZE_STYLE="colorful"
ZSH_COLORIZE_CHROMA_FORMATTER=terminal256

# vi-mode
VI_MODE_SET_CURSOR=true
MODE_INDICATOR="%F{yellow}+%f"
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true

export ZSH=$XDG_CONFIG_HOME/zsh/oh-my-zsh
source $ZSH/oh-my-zsh.sh
source $XDG_CONFIG_HOME/env/aliasrc

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
